version: "3.7"
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./app/.env.local
  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app:cached
      - ./app/node_modules/.prisma:/app/node_modules/.prisma:cached
      - node_modules:/app/node_modules
      - blitz:/app/.blitz
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 8080:80
volumes:
  db_data:
  blitz:
  node_modules:
