FROM node:lts-alpine

ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

RUN apk add --no-cache libtool autoconf automake python make g++

COPY package.json yarn.lock ./
RUN yarn

CMD yarn start:dev
